# import json
# dict = {
# 'BTC':{'name_kr':'비트코인', 'name_en':'Bitcoin'},
# 'ETH':{'name_kr':'이더리움', 'name_en':'Ethereum'},
# 'NEO':{'name_kr':'네오', 'name_en':'NEO'},
# 'MTL':{'name_kr':'메탈', 'name_en':'Metal'},
# 'LTC':{'name_kr':'라이트코인', 'name_en':'Litecoin'},
# 'XRP':{'name_kr':'리플', 'name_en':'Ripple'},
# 'ETC':{'name_kr':'이더리움클래식', 'name_en':'Ethereum Classic'},
# 'OMG':{'name_kr':'오미세고', 'name_en':'OmiseGo'},
# 'SNT':{'name_kr':'스테이터스네트워크토큰', 'name_en':'Status Network Token'},
# 'WAVES':{'name_kr':'웨이브', 'name_en':'Waves'},
# 'XEM':{'name_kr':'넴', 'name_en':'NEM'},
# 'QTUM':{'name_kr':'퀀텀', 'name_en':'Qtum'},
# 'LSK':{'name_kr':'리스크', 'name_en':'Lisk'},
# 'STEEM':{'name_kr':'스팀', 'name_en':'Steem'},
# 'XLM':{'name_kr':'스텔라루멘', 'name_en':'Lumen'},
# 'ARDR':{'name_kr':'아더', 'name_en':'Ardor'},
# 'KMD':{'name_kr':'코모도', 'name_en':'Komodo'},
# 'ARK':{'name_kr':'아크', 'name_en':'Ark'},
# 'STORJ':{'name_kr':'스토리지', 'name_en':'Storj'},
# 'GRS':{'name_kr':'그로스톨코인', 'name_en':'Groestlcoin'},
# 'REP':{'name_kr':'어거', 'name_en':'Augur'},
# 'EMC2':{'name_kr':'아인스타이늄', 'name_en':'Einsteinium'},
# 'ADA':{'name_kr':'에이다', 'name_en':'Ada'},
# 'SBD':{'name_kr':'스팀달러', 'name_en':'SteemDollars'},
# 'POWR':{'name_kr':'파워렛저', 'name_en':'Power ledger'},
# 'BTG':{'name_kr':'비트코인골드', 'name_en':'Bitcoin Gold'},
# 'ICX':{'name_kr':'아이콘', 'name_en':'Icon'},
# 'EOS':{'name_kr':'이오스', 'name_en':'EOS'},
# 'TRX':{'name_kr':'트론', 'name_en':'TRON'},
# 'SC':{'name_kr':'시아코인', 'name_en':'Siacoin'},
# 'IGNIS':{'name_kr':'이그니스', 'name_en':'Ignis'},
# 'ONT':{'name_kr':'온톨로지', 'name_en':'Ontology'},
# 'ZIL':{'name_kr':'질리카', 'name_en':'Zilliqa'},
# 'POLY':{'name_kr':'폴리매쓰', 'name_en':'Polymath'},
# 'ZRX':{'name_kr':'제로엑스', 'name_en':'0x Protocol'},
# 'LOOM':{'name_kr':'룸네트워크', 'name_en':'Loom Network'},
# 'BCH':{'name_kr':'비트코인캐시', 'name_en':'Bitcoin Cash'},
# 'ADX':{'name_kr':'애드엑스', 'name_en':'AdEx'},
# 'BAT':{'name_kr':'베이직어텐션토큰', 'name_en':'Basic Attention Token'},
# 'IOST':{'name_kr':'아이오에스티', 'name_en':'IOST'},
# 'DMT':{'name_kr':'디마켓', 'name_en':'DMarket'},
# 'RFR':{'name_kr':'리퍼리움', 'name_en':'Refereum'},
# 'CVC':{'name_kr':'시빅', 'name_en':'Civic'},
# 'IQ':{'name_kr':'에브리피디아', 'name_en':'Everipedia'},
# 'IOTA':{'name_kr':'아이오타', 'name_en':'IOTA'},
# 'MFT':{'name_kr':'메인프레임', 'name_en':'Mainframe'},
# 'ONG':{'name_kr':'온톨로지가스', 'name_en':'ONG'},
# 'GAS':{'name_kr':'가스', 'name_en':'GAS'},
# 'UPP':{'name_kr':'센티넬프로토콜', 'name_en':'Sentinel Protocol'},
# 'ELF':{'name_kr':'엘프', 'name_en':'aelf'},
# 'KNC':{'name_kr':'카이버네트워크', 'name_en':'Kyber Network'},
# 'BSV':{'name_kr':'비트코인에스브이', 'name_en':'Bitcoin SV'},
# 'THETA':{'name_kr':'쎄타토큰', 'name_en':'Theta Token'},
# 'EDR':{'name_kr':'엔도르', 'name_en':'Endor'},
# 'QKC':{'name_kr':'쿼크체인', 'name_en':'QuarkChain'},
# 'BTT':{'name_kr':'비트토렌트', 'name_en':'BitTorrent'},
# 'MOC':{'name_kr':'모스코인', 'name_en':'Moss Coin'},
# 'ENJ':{'name_kr':'엔진코인', 'name_en':'Enjin'},
# 'TFUEL':{'name_kr':'쎄타퓨엘', 'name_en':'Theta Fuel'},
# 'MANA':{'name_kr':'디센트럴랜드', 'name_en':'Decentraland'},
# 'ANKR':{'name_kr':'앵커', 'name_en':'Ankr'},
# 'AERGO':{'name_kr':'아르고', 'name_en':'Aergo'},
# 'ATOM':{'name_kr':'코스모스', 'name_en':'Cosmos'},
# 'TT':{'name_kr':'썬더토큰', 'name_en':'Thunder Token'},
# 'CRE':{'name_kr':'캐리프로토콜', 'name_en':'Carry Protocol'},
# 'SOLVE':{'name_kr':'솔브케어', 'name_en':'Solve.Care'},
# 'MBL':{'name_kr':'무비블록', 'name_en':'MovieBloc'},
# 'TSHP':{'name_kr':'트웰브쉽스', 'name_en':'12SHIPS'},
# 'WAXP':{'name_kr':'왁스', 'name_en':'WAX'},
# 'HBAR':{'name_kr':'헤데라해시그래프', 'name_en':'Hedera Hashgraph'},
# 'MED':{'name_kr':'메디블록', 'name_en':'MediBloc'},
# 'MLK':{'name_kr':'밀크', 'name_en':'MiL.k'},
# 'STPT':{'name_kr':'에스티피', 'name_en':'Standard Tokenization Protocol'},
# 'ORBS':{'name_kr':'오브스', 'name_en':'Orbs'},
# 'VET':{'name_kr':'비체인', 'name_en':'VeChain'},
# 'CHZ':{'name_kr':'칠리즈', 'name_en':'Chiliz'},
# 'PXL':{'name_kr':'픽셀', 'name_en':'PIXEL'},
# 'STMX':{'name_kr':'스톰엑스', 'name_en':'StormX'},
# 'DKA':{'name_kr':'디카르고', 'name_en':'dKargo'},
# 'HIVE':{'name_kr':'하이브', 'name_en':'Hive'},
# 'KAVA':{'name_kr':'카바', 'name_en':'Kava'},
# 'AHT':{'name_kr':'아하토큰', 'name_en':'AhaToken'},
# 'LINK':{'name_kr':'체인링크', 'name_en':'Chainlink'},
# 'XTZ':{'name_kr':'테조스', 'name_en':'Tezos'},
# 'BORA':{'name_kr':'보라', 'name_en':'BORA'},
# 'JST':{'name_kr':'저스트', 'name_en':'JUST'},
# 'CRO':{'name_kr':'크립토닷컴체인', 'name_en':'Crypto.com Chain'},
# 'TON':{'name_kr':'톤', 'name_en':'TON'},
# 'SXP':{'name_kr':'스와이프', 'name_en':'Swipe'},
# 'LAMB':{'name_kr':'람다', 'name_en':'Lambda'},
# 'HUNT':{'name_kr':'헌트', 'name_en':'HUNT'},
# 'MARO':{'name_kr':'마로', 'name_en':'Maro'},
# 'PLA':{'name_kr':'플레이댑', 'name_en':'PlayDapp'},
# 'DOT':{'name_kr':'폴카닷', 'name_en':'Polkadot'},
# 'SRM':{'name_kr':'세럼', 'name_en':'Serum'},
# 'MVL':{'name_kr':'엠블', 'name_en':'MVL'},
# 'PCI':{'name_kr':'페이코인', 'name_en':'PayCoin'},
# 'STRAX':{'name_kr':'스트라티스', 'name_en':'Stratis'},
# 'AQT':{'name_kr':'알파쿼크', 'name_en':'Alpha Quark Token'},
# 'BCHA':{'name_kr':'비트코인캐시에이비씨', 'name_en':'Bitcoin Cash ABC'},
# 'GLM':{'name_kr':'골렘', 'name_en':'Golem'},
# 'QTCON':{'name_kr':'퀴즈톡', 'name_en':'Quiztok'},
# 'SSX':{'name_kr':'썸씽', 'name_en':'SOMESING'},
# 'META':{'name_kr':'메타디움', 'name_en':'Metadium'},
# 'OBSR':{'name_kr':'옵저버', 'name_en':'Observer'},
# 'FCT2':{'name_kr':'피르마체인', 'name_en':'FirmaChain'},
# 'LBC':{'name_kr':'엘비알와이크레딧', 'name_en':'LBRY Credits'},
# 'CBK':{'name_kr':'코박토큰', 'name_en':'Cobak Token'},
# 'SAND':{'name_kr':'샌드박스', 'name_en':'The Sandbox'},
# 'HUM':{'name_kr':'휴먼스케이프', 'name_en':'Humanscape'},
# 'DOGE':{'name_kr':'도지코인', 'name_en':'Dogecoin'},
# 'STRK':{'name_kr':'스트라이크', 'name_en':'Strike'},
# 'PUNDIX':{'name_kr':'펀디엑스', 'name_en':'Pundi X'},
# 'FLOW':{'name_kr':'플로우', 'name_en':'Flow'},
# 'DAWN':{'name_kr':'던프로토콜', 'name_en':'Dawn Protocol'},
# 'AXS':{'name_kr':'엑시인피니티', 'name_en':'Axie Infinity'},
# 'STX':{'name_kr':'스택스', 'name_en':'Stacks'},
# }

# with open('j.json', 'w', encoding='UTF-8-sig') as file:
#     file.write(json.dumps(dict, ensure_ascii=False))



# #f = open('D:\.txt','w')
# #for market in coin_info.keys():
# #    f.write('\n')
# #    f.write(market)
# #    f.write('\n')
# #    for coin in coin_info[market].keys():
# #        f.write(coin)
# #        f.write(' : ')
# #        f.write(coin_info[market][coin])
# #        f.write('\n')
# #f.close()