# Generated by Django 3.0.5 on 2021-04-21 15:39

import backend.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=10)),
                ('name_kr', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=10)),
                ('name_kr', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=20)),
                ('standard', djongo.models.fields.EmbeddedField(model_container=backend.models.Standard)),
                ('target', djongo.models.fields.ArrayField(model_container=backend.models.Target)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('star_coin', djongo.models.fields.ArrayField(model_container=backend.models.Coin)),
                ('star_market', djongo.models.fields.ArrayField(model_container=backend.models.Market)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('standard', models.CharField(max_length=30)),
                ('targets', djongo.models.fields.ArrayField(model_container=backend.models.Market)),
            ],
        ),
    ]
